language: node_js
node_js:
- '8'
- '9'
- '10'
- '11'
jobs:
  include:
  - stage: test
    script: yarn run test
  - stage: lint
    script: yarn run lint
  - stage: docs
    script: yarn run docs
  - stage: coverage
    script: yarn run coverage && yarn run coverage:report
before_deploy: "yarn run build"
deploy:
- provider: npm
  email: npm@stormdesign.us
  api_key:
    secure: QXPdCU8iTNsN7Igw6/nVyY9gi2rFoTzOCLYmYFoqMafPBq0rG1LW/gLcmOlLPstPKHqGHTkWv/iVfQKw/IUaYbJaArnj8LnjVsRKWsLv9SXzZ6dGz5y30gLZHBvQFU02LdaWVpe+vebhIINcETvWoDzUyqgafxMcHzOeREgf9XbCaTsQNZhyFCX8kFAsLY9pDDt7+3Bn1pZLPEIL0dtATkcpL3tgtGlL5ZWTagLkJC5xphAAoN1i7buNiGTf85G4mX3vgi+bU6IjGy7mnVcWMi2g9O8XKjcEyvoT00eK16aFK6Qd+9pYaLmld9GnRUmbNuZ7oGMwRc6PglHWenAEnY9u48GUFS+cnaCcmxA42E6rehVGNSilPwzwTMo2r3+Kga7dA3YVqVMN7MEu2TKdzqz2GU1Jmcvtc75gMnRleiUraXqL6Ab0c+13v+VzYk3lDYgE88RCx4Rak7maA/q+XPm4cB0Q/PnXS12aYqyMRnIHhF3Mw+utZ9BnzsHoqSU55y6LsHNxwfrUoTExXwXCdjy6ek7wiKjXpefhTNasHu/shBxj0s+Kl9jChulkJUnecgaha5fHwEBhBDdRIJ3CxMnPfDgcXJFhxvytEOttQb8yabKgIr0p7UdUMjc+x0Lx84t7A2k8IFt/JQIfsPqJbuxkx7OXwYjJSzIX7eYcn40=
  on:
    tags: true
    repo: jwinnie/antipathy
- provider: surge
  project: "./docs/"
  domain: antipathy.surge.sh
  on:
    tags: true
    repo: jwinnie/antipathy
env:
  matrix:
    secure: jI/+Ms1O2pN7/Ff6tEc0zn94WOyFSibou8OY3gBbCD2mKJHsseGuJkylvXFyDc/TML9QyQF61dns/Di4/6UfxjeQaTiBV2VVTSck3dPRVM6Gz3EsLyy6DZ11xZBJ4s3/YhjHHr00m39SMYnZuETXc8wgZUzmiFnLPJ+4yEfzB43Z8pi67raqX9h6VHVmpVcr251ZqgKlBkwyC7Ef9c4l5YWLM5V/yGm9jIZmix5CvKj6C5vK0wnkWa5Xfw+zMxr1ho6P6VdTA1hPO0cVf77ZmS40CvCYvdB1KngiQwOIyhS41T6RMCCwBV32QWfowLlnRhqOobZIh91MqRfjJmOxFk1XFwA4dMQFjmEIRNJDJjM08G4g+STXs1EVGVFaGAxHLHB6b2ORS6wnnK6jorJEMhAZEzb3Stym6CQ9xf8IkLlCP8NQWU71RKnvr82OnAMbdHRCk5C0dIU4XMu6Vg4E+adJsqIaPz98teHAzfaYniVUdi6FkxZlU7t86DeqxGyICTRysPVGaCEGrfmsu5QAC7WWhxY4H1eelhwEi2joeG3ANpthspiJDaED0Q9CEH9OH5oHpDN/KwuwJ9/RmDifpUaHa7WeGsxB20Vp8K6WqZgAuhNVzLXO2fT86+DC+7ztSr5leFGJcAhDZ+z8RZMwzr4AZ2hbTfRqfTNPKYFjeKM=
