language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
jobs:
  - stage: test
    script: yarn run test
  - stage: lint
    script: yarn run lint
  - stage: docs
    script: yarn run docs
  - stage: coverage
    script: yarn run coverage